sudo: required
language: java
script: mvn clean -P acceptance scoverage:report
jdk:
  - oraclejdk8
services:
  - docker
branches:
 only:
  - master
notifications:
  email:
  - pablo.gonzalez.granados@gmail.com
